apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-netapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin-netapp
  template:
    metadata:
      labels:
        app: pgadmin-netapp
    spec:
      containers:
        - name: pgadmin-netapp
          image: dpage/pgadmin4:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: uma-netapp-pgadmin-configmap
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: uma-netapp-pgadmin-configmap
                  key: PGADMIN_DEFAULT_PASSWORD