apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  # User DB
  POSTGRES_DB: netappdb
  # Db user
  POSTGRES_USER: netapp
  # Db password
  POSTGRES_PASSWORD: secret
  # Db pgdata
  PGDATA: /var/lib/postgresql/data