apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
spec:
  storageClassName: kadalu.storage-pool-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi